version: "3.3"

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  findev:
    image: findev/fin/demo:latest
    ports:
      - "8180:8180"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USER: app
      DB_PASSWORD: app

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      SWAGGER_JSON: /foo/swagger.json -v /bar:/foo swaggerapi/swagger-ui
      BASE_URL: /api/doc
    labels:
      - traefik.enable=true
      - traefik.http.routers.swagger-ui.rule=PathPrefix(`/api/doc`)
      - traefik.http.routers.swagger-ui.entrypoints=web
      - traefik.http.services.swagger-ui.loadbalancer.server.port=8080


volumes:
  data:
  logs: