#version: "3.3"
#
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  findev:
    image: findev/fin/demo:latest
    ports:
      - "8180:8180"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USER: app
      DB_PASSWORD: app

  frontend:
    image: abracadanis/findev-frontend
    ports:
      - "8080:3000"
    depends_on:
      - findev

volumes:
  data:
  logs:
