/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserEntity } from './UserEntity';
import {
    UserEntityFromJSON,
    UserEntityFromJSONTyped,
    UserEntityToJSON,
    UserEntityToJSONTyped,
} from './UserEntity';

/**
 * 
 * @export
 * @interface ProjectSo
 */
export interface ProjectSo {
    /**
     * 
     * @type {string}
     * @memberof ProjectSo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSo
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectSo
     */
    imageId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectSo
     */
    id?: number;
    /**
     * 
     * @type {Set<UserEntity>}
     * @memberof ProjectSo
     */
    users?: Set<UserEntity>;
}

/**
 * Check if a given object implements the ProjectSo interface.
 */
export function instanceOfProjectSo(value: object): value is ProjectSo {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProjectSoFromJSON(json: any): ProjectSo {
    return ProjectSoFromJSONTyped(json, false);
}

export function ProjectSoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'id': json['id'] == null ? undefined : json['id'],
        'users': json['users'] == null ? undefined : (new Set((json['users'] as Array<any>).map(UserEntityFromJSON))),
    };
}

export function ProjectSoToJSON(json: any): ProjectSo {
    return ProjectSoToJSONTyped(json, false);
}

export function ProjectSoToJSONTyped(value?: ProjectSo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'imageId': value['imageId'],
        'id': value['id'],
        'users': value['users'] == null ? undefined : (Array.from(value['users'] as Set<any>).map(UserEntityToJSON)),
    };
}

