/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectEntity } from './ProjectEntity';
import {
    ProjectEntityFromJSON,
    ProjectEntityFromJSONTyped,
    ProjectEntityToJSON,
    ProjectEntityToJSONTyped,
} from './ProjectEntity';

/**
 * 
 * @export
 * @interface UserSo
 */
export interface UserSo {
    /**
     * 
     * @type {string}
     * @memberof UserSo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserSo
     */
    surname: string;
    /**
     * 
     * @type {Set<ProjectEntity>}
     * @memberof UserSo
     */
    projects?: Set<ProjectEntity> | null;
    /**
     * 
     * @type {number}
     * @memberof UserSo
     */
    id?: number;
}

/**
 * Check if a given object implements the UserSo interface.
 */
export function instanceOfUserSo(value: object): value is UserSo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    return true;
}

export function UserSoFromJSON(json: any): UserSo {
    return UserSoFromJSONTyped(json, false);
}

export function UserSoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'surname': json['surname'],
        'projects': json['projects'] == null ? undefined : (new Set((json['projects'] as Array<any>).map(ProjectEntityFromJSON))),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UserSoToJSON(json: any): UserSo {
    return UserSoToJSONTyped(json, false);
}

export function UserSoToJSONTyped(value?: UserSo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'projects': value['projects'] == null ? undefined : (Array.from(value['projects'] as Set<any>).map(ProjectEntityToJSON)),
        'id': value['id'],
    };
}

